"""
MTF Paper Trading
-----------------
Tracks paper trades generated by the MTF Adaptive Engine.

Each MTFPaperTrade records the full engine snapshot + forward outcome.
Resolution simulates T1 / T2 partial exit and trailing stop.

Exit logic (multi-target):
  - Hits T1  → close 50% at T1, trail SL to entry (breakeven)
  - Hits T2  → close remaining 50% at T2
  - Hits SL  → full loss on remaining position
  - N bars   → square off at last close (EOD)

PnL is reported in ₹ points (entry-reference, not leveraged).
R-multiple uses original risk (entry - stop).
"""
from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from typing import Optional
import pandas as pd


MTF_PAPER_SCHEMA = [
    "id", "logged_at", "trade_type", "action", "bias",
    "confidence_score", "decision", "leverage",
    "entry", "stop", "target1", "target2",
    "position_size", "risk_per_trade",
    "setup_type", "trend_score", "setup_score", "conf_score", "volume_ratio",
    "track",                      # "auto" | "manual"
    "status",                     # "open" | "closed" | "unresolved"
    "exit_price_t1", "exit_price_t2", "exit_price_sl",
    "exit_reason",                # "t1+t2" | "t1+sl" | "sl" | "eod" | "unresolved"
    "pnl_points",                 # total ₹ per share (avg across partial exits)
    "r_multiple",
    "notes",
]


@dataclass
class MTFPaperTrade:
    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    logged_at: str = ""
    trade_type: str = "intraday"   # "intraday" | "margin"
    action: str = "buy"
    bias: str = "bullish"
    confidence_score: float = 0.0
    decision: str = "avoid"
    leverage: float = 1.0
    entry: float = 0.0
    stop: float = 0.0
    target1: float = 0.0
    target2: float = 0.0
    position_size: int = 0
    risk_per_trade: float = 0.0
    setup_type: str = "none"
    trend_score: float = 50.0
    setup_score: float = 50.0
    conf_score: float = 50.0
    volume_ratio: float = 1.0
    track: str = "manual"
    status: str = "open"
    exit_price_t1: Optional[float] = None
    exit_price_t2: Optional[float] = None
    exit_price_sl: Optional[float] = None
    exit_reason: Optional[str] = None
    pnl_points: Optional[float] = None
    r_multiple: Optional[float] = None
    notes: str = ""

    def to_dict(self) -> dict:
        return {k: getattr(self, k) for k in MTF_PAPER_SCHEMA}


def resolve_mtf_paper_trade(
    trade: MTFPaperTrade,
    forward_bars: pd.DataFrame,
    margin_bars: int = 5,
) -> MTFPaperTrade:
    """
    Simulate multi-target exit on forward_bars.

    Parameters
    ----------
    trade        : open MTFPaperTrade
    forward_bars : OHLCV DataFrame (daily or LTF bars after entry)
    margin_bars  : max bars before EOD square-off

    Returns
    -------
    Resolved MTFPaperTrade (mutated in-place and returned)
    """
    if forward_bars is None or forward_bars.empty:
        trade.status = "unresolved"
        trade.exit_reason = "unresolved"
        return trade

    cols = {c.lower(): c for c in forward_bars.columns}
    def _col(name):
        return cols.get(name, name)

    entry   = trade.entry
    stop    = trade.stop
    t1      = trade.target1
    t2      = trade.target2
    action  = trade.action       # "buy" | "sell"
    risk    = abs(entry - stop)
    if risk <= 0:
        trade.status = "unresolved"
        trade.exit_reason = "zero_risk"
        return trade

    t1_hit = False
    t1_exit = None
    bars = forward_bars.head(margin_bars)

    for _, bar in bars.iterrows():
        h = float(bar[_col("high")])
        l = float(bar[_col("low")])

        if action == "buy":
            # SL first (worst case — bar gaps through both)
            if l <= stop:
                sl_exit = stop
                if t1_hit:
                    # 50% exited at T1, 50% stopped at SL
                    pnl = 0.5 * (t1_exit - entry) + 0.5 * (sl_exit - entry)
                    trade.exit_price_sl = sl_exit
                    trade.exit_reason   = "t1+sl"
                else:
                    pnl = sl_exit - entry
                    trade.exit_price_sl = sl_exit
                    trade.exit_reason   = "sl"
                trade.pnl_points = round(pnl, 2)
                trade.r_multiple = round(pnl / risk, 2)
                trade.status     = "closed"
                return trade

            if not t1_hit and h >= t1:
                t1_hit   = True
                t1_exit  = t1
                trade.exit_price_t1 = t1
                # Trail SL to breakeven
                stop = entry

            if t1_hit and h >= t2:
                pnl = 0.5 * (t1_exit - entry) + 0.5 * (t2 - entry)
                trade.exit_price_t2 = t2
                trade.exit_reason   = "t1+t2"
                trade.pnl_points    = round(pnl, 2)
                trade.r_multiple    = round(pnl / risk, 2)
                trade.status        = "closed"
                return trade

        else:  # sell
            if h >= stop:
                sl_exit = stop
                if t1_hit:
                    pnl = 0.5 * (entry - t1_exit) + 0.5 * (entry - sl_exit)
                    trade.exit_price_sl = sl_exit
                    trade.exit_reason   = "t1+sl"
                else:
                    pnl = entry - sl_exit
                    trade.exit_price_sl = sl_exit
                    trade.exit_reason   = "sl"
                trade.pnl_points = round(pnl, 2)
                trade.r_multiple = round(pnl / risk, 2)
                trade.status     = "closed"
                return trade

            if not t1_hit and l <= t1:
                t1_hit  = True
                t1_exit = t1
                trade.exit_price_t1 = t1
                stop = entry

            if t1_hit and l <= t2:
                pnl = 0.5 * (entry - t1_exit) + 0.5 * (entry - t2)
                trade.exit_price_t2 = t2
                trade.exit_reason   = "t1+t2"
                trade.pnl_points    = round(pnl, 2)
                trade.r_multiple    = round(pnl / risk, 2)
                trade.status        = "closed"
                return trade

    # EOD square-off at last close
    last_close = float(bars.iloc[-1][_col("close")])
    if action == "buy":
        if t1_hit:
            pnl = 0.5 * (t1_exit - entry) + 0.5 * (last_close - entry)
            trade.exit_reason = "t1+eod"
        else:
            pnl = last_close - entry
            trade.exit_reason = "eod"
    else:
        if t1_hit:
            pnl = 0.5 * (entry - t1_exit) + 0.5 * (entry - last_close)
            trade.exit_reason = "t1+eod"
        else:
            pnl = entry - last_close
            trade.exit_reason = "eod"

    trade.exit_price_t2 = last_close
    trade.pnl_points    = round(pnl, 2)
    trade.r_multiple    = round(pnl / risk, 2)
    trade.status        = "closed"
    return trade


def mtf_paper_log_to_df(log: list[MTFPaperTrade]) -> pd.DataFrame:
    if not log:
        return pd.DataFrame(columns=MTF_PAPER_SCHEMA)
    return pd.DataFrame([t.to_dict() for t in log])


def summarise_mtf_track(df: pd.DataFrame, track: str) -> dict:
    """Summarise closed trades for a given track ('auto' | 'manual')."""
    sub = df[df["track"] == track].copy() if not df.empty and "track" in df.columns else pd.DataFrame()
    if sub.empty:
        return {"trades": 0, "wins": 0, "losses": 0, "win_rate": 0.0,
                "total_pnl": 0.0, "avg_r": 0.0, "avg_conf": 0.0}
    closed = sub[sub["status"] == "closed"]
    pnl    = pd.to_numeric(closed["pnl_points"], errors="coerce")
    r_vals = pd.to_numeric(closed["r_multiple"], errors="coerce").dropna()
    conf   = pd.to_numeric(closed["confidence_score"], errors="coerce").dropna()
    wins   = pnl[pnl > 0]
    losses = pnl[pnl <= 0]
    return {
        "trades"   : len(closed),
        "wins"     : len(wins),
        "losses"   : len(losses),
        "win_rate" : len(wins) / len(closed) if len(closed) > 0 else 0.0,
        "total_pnl": round(float(pnl.sum()), 2),
        "avg_r"    : round(float(r_vals.mean()), 2) if not r_vals.empty else 0.0,
        "avg_conf" : round(float(conf.mean()), 1)   if not conf.empty  else 0.0,
    }
